# Generated by Django 4.2.25 on 2025-10-29 13:12

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Article',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('content', models.TextField()),
                ('author_name', models.CharField(max_length=100)),
                ('external_id', models.IntegerField(blank=True, null=True, unique=True)),
            ],
        ),
    ]
